VENV_PATH := /home/vagrant/venv/bin
PROJ_NAME := {{ proj_name }}

runserver:
	$(VENV_PATH)/python manage.py runserver 0.0.0.0:8000

start:
	$(VENV_PATH)/gunicorn --preload -D -b 127.0.0.1:8000 $(PROJ_NAME).wsgi:application

pep8:
	$(VENV_PATH)/pep8 --exclude=*migrations*,*settings_local.py* --max-line-length=119 --show-source  $(PROJ_NAME)/

pyflakes:
	$(VENV_PATH)/pylama --skip=*migrations* -l pyflakes $(PROJ_NAME)/

lint: pep8 pyflakes

test:
	$(VENV_PATH)/python manage.py test -v 2 --noinput

ci_test: test lint

wheel_install:
	$(VENV_PATH)/pip install --no-index -f wheels/ -r requirements.txt
{% if CELERY %}
runcelery:
	$(VENV_PATH)/celery -A $(PROJ_NAME) worker -l info -B -s ./var/celerybeat-schedule

runcelery_multi:
	$(VENV_PATH)/celery multi restart $(PROJ_NAME)_worker \
		-A $(PROJ_NAME) -l info -B -s ./var/celerybeat-schedule \
			--logfile="./var/celery_%n.log" \
				--pidfile="./var/celery_%n.pid"

stopcelery_multi:
	kill `cat var/celery_$(PROJ_NAME)_worker.pid` || true

restart_celery: stopcelery_multi runcelery_multi
{% endif %}
{# keep trailing newline #}
