VENV_PATH := /home/vagrant/venv/bin

runserver:
	$(VENV_PATH)/python manage.py runserver 0.0.0.0:8000

start:
	$(VENV_PATH)/gunicorn --preload -D -b 127.0.0.1:8000 {{ proj_name }}.wsgi:application

pep8:
	$(VENV_PATH)/pep8 --exclude=*migrations*,*settings_local.py* --max-line-length=119 --show-source  {{ proj_name }}/

pyflakes:
	$(VENV_PATH)/pylama --skip=*migrations* -l pyflakes {{ proj_name }}/

lint:
	make pep8
	make pyflakes

test:
	$(VENV_PATH)/python manage.py test {{ proj_name }} -v 2 --noinput

ci_test:
	make test
	make lint

wheel_install:
	$(VENV_PATH)/pip install --no-index -f wheels/ -r requirements.txt
{% if CELERY %}
runcelery:
	$(VENV_PATH)/celery -A {{ proj_name }} worker -l info -B -s ./var/celerybeat-schedule

runcelery_multi:
	$(VENV_PATH)/celery multi restart {{ proj_name }}_worker \
		-A {{ proj_name }} -l info -B -s ./var/celerybeat-schedule \
			--logfile="./var/celery_%n.log" \
				--pidfile="./var/celery_%n.pid"
{% endif %}
{# keep trailing newline #}
